FROM docker.io/library/archlinux:base-devel

RUN sed -i /etc/pacman.conf -e 's/NoProgress/#NoProgress/' -e '/NoExtract.*locale/d'
# && \
# printf '%s\n%s\n' 'NoExtract = !usr/share/locale/ja/*' 'NoExtract = !usr/share/i18n/locales/ja_JP/*' >> /etc/pacman.conf

COPY --chmod=644 mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu --noconfirm archlinux-keyring && \
  pacman -S busybox git glibc moreutils pacman-contrib sudo

COPY --chmod=644 locale.gen /etc/locale.gen
RUN locale-gen

RUN useradd -m -s /usr/bin/nologin user && \
  printf '%s\n' 'user ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
USER user

RUN git clone https://aur.archlinux.org/yay-bin /home/user/yay
RUN cd /home/user/yay && makepkg -sir --noconfirm
COPY --chown=user:user yay.json /home/user/.config/yay/config.json

COPY --chmod=755 files.sh /usr/bin/files.sh

RUN mkdir /home/user/workdir
WORKDIR /home/user/workdir