VERSION --use-chmod 0.6
FROM docker.io/library/archlinux:base-devel

RUN sed -i /etc/pacman.conf -e 's/NoProgress/#NoProgress/' -e '/NoExtract.*locale/d'
# && \
# printf '%s\n%s\n' 'NoExtract = !usr/share/locale/ja/*' 'NoExtract = !usr/share/i18n/locales/ja_JP/*' >> /etc/pacman.conf
COPY --chmod=644 mirrorlist /etc/pacman.d/mirrorlist
RUN pacman -Sy glibc git moreutils

COPY --chmod=644 locale.gen /etc/locale.gen
RUN locale-gen

RUN groupadd --gid 65532 nonroot && \
  useradd --uid 65532 --gid 65532 -m -s /usr/bin/nologin nonroot && \
  printf '%s\n' 'nonroot ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
USER nonroot
WORKDIR /home/nonroot

ARG pacman=yay
GIT CLONE --branch master https://aur.archlinux.org/${pacman}-bin.git /tmp/aur-helper
RUN cd /tmp/aur-helper && makepkg -sir --noconfirm
ARG pacman=$pacman --noconfirm

$pacman -S s6-rc

container:
  ARG date=$(date --utc +%Y%m%d%H%M)
  SAVE IMAGE --push registry.1inguini.com/library/builder:latest
  SAVE IMAGE --push registry.1inguini.com/library/builder:$date

VERSION:
  COMMAND
  ARG --required target
  ARG --required outfile
  RUN $pacman -Qi "$target" | grep 'Version' | grep -o '[^ ]*$' > "$outfile"

FILELIST:
  COMMAND
  ARG --required file

  RUN cat "$file" | xargs ldd | grep -Po ' /[^ ]*' | sed -e 's/^ //' | sponge -a "$file"
  RUN echo '/usr/lib/locale/locale-archive' >> "$file" && \
    echo '/etc/ld.so.cache' >> "$file" && \
    echo '/lib64/ld-linux-x86-64.so.2' >> "$file"

  RUN xargs readlink -f <"$file" | sponge -a "$file"
  RUN sort <"$file" | uniq | sponge "$file"

ROOTFS:
  COMMAND
  ARG --required infile

  RUN mkdir -p /tmp/rootfs/
  RUN sudo tar --ignore-failed-read --no-recursion -C / -T "$infile" -cpf - | \
    sudo tar -C /tmp/rootfs/ -xpf -
  RUN sudo ldconfig -r /tmp/rootfs

  SAVE ARTIFACT --keep-own /tmp/rootfs

REMOVE_SH:
  COMMAND
  ARG --required dir
  RUN for file in $(find $dir -type f); do \
      if [ $(file -L --mime-type $file | grep -o '[^ ]*$') = 'text/x-shellscript' ]; then \
        sudo rm "$file"; \
      fi; \
    done