VERSION --use-chmod 0.6
FROM docker.io/library/archlinux:base-devel

ARG date=$(date --rfc-3339=date)
ARG seconds=$(date --rfc-3339=seconds)

all:
  BUILD +buildenv

nonroot:
  RUN groupadd --gid 65532 nonroot && \
    useradd --uid 65532 --gid 65532 -m -s /usr/bin/nologin nonroot && \
    echo 'nonroot ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
  USER nonroot
  WORKDIR /home/nonroot

pacman:
  FROM +nonroot
  RUN sudo sed -i /etc/pacman.conf -e 's/NoProgress/#NoProgress/' -e '/^NoExtract/d' \
    -e '$aNoExtract  = etc/systemd/*' \
    -e '$aNoExtract  = usr/share/systemd/*' \
    -e '$aNoExtract  = usr/share/man/*' \
    -e '$aNoExtract  = usr/share/help/*' \
    -e '$aNoExtract  = usr/share/doc/*' \
    -e '$aNoExtract  = usr/share/gtk-doc/*' \
    -e '$aNoExtract  = usr/share/info/*' \
    -e '$aNoExtract  = usr/share/i18n/*' \
    -e '$aNoExtract  = !usr/share/i18n/charmaps/UTF-8.gz' \
    -e '$aNoExtract  = !usr/share/i18n/locales/en_US !usr/share/i18n/locales/ja_JP' \
    -e '$aNoExtract  = usr/share/locale/*' \
    -e '$aNoExtract  = !usr/share/locale/en !usr/share/locale/ja' \
    -e '$aNoExtract  = usr/share/X11/*' \
    -e '$aNoExtract  = usr/share/systemd/*' \
    -e '$aNoExtract  = usr/share/bash-completion/*' \
    -e '$aNoExtract  = usr/share/fish/*' \
    -e '$aNoExtract  = usr/share/zsh/*'

  COPY --chmod=644 --chown=root:root mirrorlist /etc/pacman.d/mirrorlist
  RUN sudo pacman --noconfirm -Sy
  ENV pacman=sudo pacman --noconfirm

aur-helper:
  FROM +pacman
  GIT CLONE --branch master https://aur.archlinux.org/yay-bin.git aur-helper
  WORKDIR aur-helper
  RUN makepkg --noconfirm -sir
  WORKDIR ../
  ENV pacman=yay --noconfirm

locale-archive:
  FROM +pacman
  RUN $pacman -S glibc
  RUN sudo sed -i /etc/locale.gen \
    -e '$aen_US.UTF-8 UTF-8' \
    -e '$aja_JP.UTF-8 UTF-8'
  RUN sudo locale-gen
  SAVE ARTIFACT --keep-own /usr/lib/locale/locale-archive

buildenv:
  FROM +aur-helper
  COPY --keep-own +locale-archive/locale-archive /usr/lib/locale/
  RUN $pacman -S git moreutils rsync
  ENV cpr='rsync --archive --acls --xattrs -hh --partial --info=stats1,progress2 --modify-window=1 --no-inc-recursive'
  DO +PUSH --name=builder

VERSION:
  COMMAND
  ARG --required target
  ARG --required outfile
  RUN $pacman -Qi $target | grep 'Version' | grep -o '[^ ]*$' > $outfile
  SAVE ARTIFACT $outfile

PACKAGE:
  COMMAND
  ARG --required targets
  ARG aur=no
  IF [ $aur = 'yes' ]
    FROM +aur-helper
  ELSE
    FROM +pacman
  END
  RUN mkdir rootfs && \
    $pacman -S --root rootfs --dbpath=/var/lib/pacman $targets
  SAVE ARTIFACT --keep-own rootfs

ROOTFS:
  COMMAND
  ARG infile=files.txt
  ARG save=yes
  RUN touch $infile && cat $infile | xargs ldd | grep -Po ' /[^ ]*' | sed -e 's/^ //' | sponge -a $infile
  RUN f=( \
      '/usr/lib/locale/locale-archive' \
      '/lib64/ld-linux-x86-64.so.2' \
    ) && printf '%s\n' ${f[@]} >> $infile

  RUN xargs readlink -f <$infile | sponge -a $infile
  RUN sort <$infile | uniq | sed -e 's:^/::' | sponge $infile

  RUN sudo mkdir -p rootfs/etc
  RUN sudo tar --ignore-failed-read --no-recursion -C / -T $infile -cpf - | \
    sudo tar -C rootfs/ -xpf -
  RUN sudo ldconfig -r rootfs

  IF [ $save = 'yes' ]
    SAVE ARTIFACT --keep-own rootfs
  END

REMOVE_SH:
  COMMAND
  ARG --required dir
  RUN for file in $(find $dir -type f); do \
      if [ $(file -L --mime-type $file | grep -o '[^ ]*$') = 'text/x-shellscript' ]; then \
        sudo rm $file; \
      fi; \
    done

PUSH:
  COMMAND
  ARG --required name
  ARG tag=$date
  LABEL org.opencontainers.image.created=$seconds
  LABEL org.opencontainers.image.authors="1inguini <9647142@gmail.com>"
  LABEL org.opencontainers.image.url=https://registry.1inguini.com/library/$name
  LABEL org.opencontainers.image.url=https://hub.docker.com/repository/docker/1inguini/$name
  LABEL org.opencontainers.image.documentation=https://git.1inguini.com/1inguini/kube-manifest/$name
  LABEL org.opencontainers.image.documentation=https://github.com/1inguini/kube-manifest/$name
  LABEL org.opencontainers.image.source=https://git.1inguini.com/1inguini/kube-manifest/$name
  LABEL org.opencontainers.image.source=https://github.com/1inguini/kube-manifest/$name
  SAVE IMAGE --push \
    # ghcr.io/1inguini/kube-manifest/$name:latest \
    # ghcr.io/1inguini/kube-manifest/$name:$tag \
    # docker.io/1inguini/$name:latest \
    # docker.io/1inguini/$name:$tag \
    registry.1inguini.com/library/$name:latest \
    registry.1inguini.com/library/$name:$tag
