VERSION --use-chmod 0.6
IMPORT ../base
IMPORT ../builder
FROM builder+buildenv

RUN $pacman -S jre-openjdk-headless
DO builder+VERSION --target=jre-openjdk-headless --outfile=version.txt
ARG version=$(cat version.txt)

all:
  BUILD +container

rootfs:
  RUN mkdir rootfs && sudo mkdir rootfs/usr
  RUN sudo $cpr /usr/lib/jvm/java-19-openjdk/. rootfs/usr/.
  RUN sudo $cpr /usr/lib/jvm/java-19-openjdk/. /usr/.
  RUN $pacman -Qql jre-openjdk-headless | grep -Po '(?<=openjdk)/(lib/.*|conf)$' | \
    sed -e 's:^:/usr:' >> files.txt
  RUN pacman -Qql jre-openjdk-headless | grep '/etc' >> files.txt
  RUN sudo mkdir rootfs/etc && echo '/usr/lib/server' | sudo tee rootfs/etc/ld.so.conf
  DO builder+ROOTFS --infile=files.txt

container:
  FROM base+scratch
  COPY --keep-own +rootfs/rootfs /
  ENTRYPOINT [ "/usr/bin/java", "-jar" ]
  SAVE IMAGE --push registry.1inguini.com/library/openjdk:latest
  SAVE IMAGE --push registry.1inguini.com/library/openjdk:$version
