VERSION 0.6
IMPORT ../builder
FROM builder+base

DO builder+INSTALL --packages=mariadb

DO builder+VERSION --target=mariadb --outfile=version.txt
ARG version=$(cat version.txt)

rootfs:
  RUN mkdir -p /tmp/rootfs/run/mysqld/
  RUN $pacman -Qql mariadb | \
    grep -E '(/etc|/usr/(bin|share/mysql|lib/(mysql|security|sysusers.d))).*[^/]$' > files.txt
  DO builder+FILELIST --file=files.txt
  DO builder+ROOTFS --infile=files.txt

no-sh:
  FROM +rootfs
  DO builder+REMOVE_SH --dir=/tmp/rootfs/usr/bin
  SAVE ARTIFACT --keep-own /tmp/rootfs

container:
  FROM gcr.io/distroless/static:nonroot

  COPY --keep-own +no-sh/rootfs /

  ENTRYPOINT [ "/usr/bin/mariadbd" ]

  SAVE IMAGE --push registry.1inguini.com/library/mariadb:latest
  SAVE IMAGE --push registry.1inguini.com/library/mariadb:$version

var:
  COPY --keep-own +rootfs/rootfs /tmp/rootfs

  RUN sudo mariadb-install-db --user=nonroot \
    --basedir=/tmp/rootfs/usr --datadir=/tmp/rootfs/var/lib/mysql

  COPY install.sql install.sql
  RUN mariadbd --socket /tmp/rootfs/run/mysqld/mysql.sock \
    --basedir=/tmp/rootfs/usr --datadir=/tmp/rootfs/var/lib/mysql & sleep 2 && \
    mariadb -u nonroot --socket /tmp/rootfs/run/mysqld/mysql.sock -e "$(cat install.sql)" && \
    killall mariadbd
  
  SAVE ARTIFACT --keep-own /tmp/rootfs/var

var-container:
  FROM busybox:latest
  COPY --keep-own +var/ /

  ENTRYPOINT ["/bin/cp", "-rn", "/var/lib/mysql"]
  CMD [ "/mnt" ]
  VOLUME /var/lib/mysql
  SAVE IMAGE --push registry.1inguini.com/library/mariadb/var:latest
  SAVE IMAGE --push registry.1inguini.com/library/mariadb/var:$version

all:
  BUILD +container
  BUILD +var-container
