VERSION 0.6
FROM registry.1inguini.com/library/builder:latest
ARG gitbucket_ver=4.38.3

gitbucket.war:
  RUN curl -LO "https://github.com/gitbucket/gitbucket/releases/download/$gitbucket_ver/gitbucket.war"
  # curl -L -o gitbucket.war.sha256 \
  # 'https://github.com/gitbucket/gitbucket/releases/download/4.38.3/gitbucket.war.sha256'
  # sha256sum gitbucket.war
  SAVE ARTIFACT gitbucket.war

plugins:
  # plugins
  RUN curl --parallel --create-dirs --output-dir plugins -L \
    -O 'https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin/releases/download/4.35.0/gitbucket-commitgraphs-plugin_2.13-4.35.0.jar' \
    -O 'https://github.com/mrkm4ntr/gitbucket-network-plugin/releases/download/1.9.2/gitbucket-network-plugin_2.13-1.9.2.jar' \
    -O 'https://github.com/codelibs/gitbucket-fess-plugin/releases/download/gitbucket-fess-plugin-1.7.0/gitbucket-fess-plugin_2.13-1.7.0.jar' \
    -O 'https://github.com/yoshinorin/gitbucket-monitoring-plugin/releases/download/v5.1.0/gitbucket-monitorting-plugin-5.1.0.jar' \
    -O 'https://github.com/alexandremenif/gitbucket-mirror-plugin/releases/download/v1.4.0/gitbucket-mirror-plugin-1.4.0.jar' \
    -O 'https://github.com/gitbucket-plugins/gitbucket-explorer-plugin/releases/download/9.0.0/gitbucket-explorer-plugin-9.0.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-code-highlighter-plugin/releases/download/v1.6.0/gitbucket-code-highlighter-plugin-1.6.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-popovers-plugin/releases/download/v1.0.0/gitbucket-popovers-plugin-1.0.0.jar' \
    -O 'https://github.com/kounoike/gitbucket-html5media-plugin/releases/download/1.2.2/gitbucket-html5media-plugin-1.2.2.jar' \
    -O 'https://github.com/onukura/gitbucket-swagger-plugin/releases/download/1.0.7/gitbucket-swagger-plugin-1.0.7.jar'
  SAVE ARTIFACT plugins

git: # only git binary, requires ld, libc, libpthread, libz
  FROM docker.io/bitnami/git
  SAVE ARTIFACT /opt/bitnami/git/bin/git

container:
  FROM gcr.io/distroless/java11-debian11:nonroot

  COPY +gitbucket.war/gitbucket.war gitbucket.war
  COPY +plugins/plugins .gitbucket/plugins

  ENV LANG="ja_JP.UTF-8"

  CMD [ "gitbucket.war", "--port=8080" ]
  SAVE IMAGE gitbucket

push:
  FROM +container
  SAVE IMAGE --push registry.1inguini.com/library/gitbucket:$gitbucket_ver
  SAVE IMAGE --push registry.1inguini.com/library/gitbucket:latest