VERSION --use-chmod 0.6
IMPORT ../base
IMPORT ../bin
IMPORT ../builder
IMPORT ../mariadb
FROM builder+buildenv

ARG version=4.38.4
ARG kube=yes

all:
  BUILD +container
  IF [ $kube = yes ]
    BUILD +home-init-container
    BUILD mariadb+container --kube=$kube
    COPY +secret/secret .
    ARG secret=$(cat secret)
    BUILD mariadb+datadir-container --name=gitbucket/mariadb-datadir \
      --sql="CREATE DATABASE gitbucket;
      GRANT ALL PRIVILEGES ON gitbucket.* TO 'nonroot' @'localhost' IDENTIFIED VIA ed25519 USING PASSWORD('$secret');"
  END

secret:
  RUN head -c 32 /dev/random | base64 --wrap=0 > secret
  SAVE ARTIFACT secret


gitbucket.war:
  RUN curl -LO "https://github.com/gitbucket/gitbucket/releases/download/$version/gitbucket.war"
  SAVE ARTIFACT gitbucket.war

plugins:
  RUN curl --parallel --create-dirs --output-dir plugins -L \
    -O 'https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin/releases/download/4.35.0/gitbucket-commitgraphs-plugin_2.13-4.35.0.jar' \
    -O 'https://github.com/mrkm4ntr/gitbucket-network-plugin/releases/download/1.9.2/gitbucket-network-plugin_2.13-1.9.2.jar' \
    -O 'https://github.com/codelibs/gitbucket-fess-plugin/releases/download/gitbucket-fess-plugin-1.7.0/gitbucket-fess-plugin_2.13-1.7.0.jar' \
    -O 'https://github.com/yoshinorin/gitbucket-monitoring-plugin/releases/download/v5.1.0/gitbucket-monitorting-plugin-5.1.0.jar' \
    -O 'https://github.com/alexandremenif/gitbucket-mirror-plugin/releases/download/v1.4.0/gitbucket-mirror-plugin-1.4.0.jar' \
    -O 'https://github.com/gitbucket-plugins/gitbucket-explorer-plugin/releases/download/9.0.0/gitbucket-explorer-plugin-9.0.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-code-highlighter-plugin/releases/download/v1.6.0/gitbucket-code-highlighter-plugin-1.6.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-popovers-plugin/releases/download/v1.0.0/gitbucket-popovers-plugin-1.0.0.jar' \
    -O 'https://github.com/kounoike/gitbucket-html5media-plugin/releases/download/1.2.2/gitbucket-html5media-plugin-1.2.2.jar' \
    -O 'https://github.com/onukura/gitbucket-swagger-plugin/releases/download/1.0.7/gitbucket-swagger-plugin-1.0.7.jar'
  SAVE ARTIFACT plugins

git:
  RUN $pacman -S git
  RUN echo $(which git) >> files.txt
  DO builder+ROOTFS --infile=files.txt

home:
  COPY database.conf .gitbucket/
  COPY +secret/secret .
  RUN sed -e "s:secret:$(cat secret):" -i .gitbucket/database.conf
  COPY +plugins/plugins .gitbucket/plugins
  SAVE ARTIFACT .gitbucket

rootfs:
  COPY +gitbucket.war/gitbucket.war rootfs/home/nonroot/
  COPY +git/rootfs rootfs
  COPY bin+execline/background rootfs/usr/bin/
  COPY (mariadb+rootfs/rootfs --kube=$kube) rootfs
  IF [ $kube = no ]
    COPY +home/.gitbucket rootfs/home/nonroot/.gitbucket
  END
  SAVE ARTIFACT rootfs

home-init-container:
  FROM base+cp-init
  COPY --chown=nonroot:nonroot +home/.gitbucket /contents
  DO builder+PUSH --name=gitbucket/home-init

container:
  IF [ $kube = 'yes' ]
    ARG suffix=/main
  END
  FROM ../openjdk+container
  COPY +rootfs/rootfs /
  ENTRYPOINT [ "if", " loopwhilex", " -x", " 0", " test", " -e", " /var/lib/mysql/mysql", "", "background", " mariadbd", "", "if", " loopwhilex", " -x", " 0", " test", " -e", " /run/mysqld/mysqld.sock", "", "java", "-jar" ]
  CMD [ "gitbucket.war", "--port=8080" ]
  EXPOSE 8080
  LABEL org.opencontainers.image.description="gitbucket with mariadb"
  DO builder+PUSH --name=gitbucket$suffix --tag=$version
