VERSION --use-chmod 0.6
IMPORT ../base
IMPORT ../builder 
FROM builder+buildenv

ARG version=4.38.3

all:
  BUILD +container

gitbucket.war:
  RUN curl -LO "https://github.com/gitbucket/gitbucket/releases/download/$version/gitbucket.war"
  SAVE ARTIFACT gitbucket.war

plugins:
  # plugins
  RUN curl --parallel --create-dirs --output-dir plugins -L \
    -O 'https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin/releases/download/4.35.0/gitbucket-commitgraphs-plugin_2.13-4.35.0.jar' \
    -O 'https://github.com/mrkm4ntr/gitbucket-network-plugin/releases/download/1.9.2/gitbucket-network-plugin_2.13-1.9.2.jar' \
    -O 'https://github.com/codelibs/gitbucket-fess-plugin/releases/download/gitbucket-fess-plugin-1.7.0/gitbucket-fess-plugin_2.13-1.7.0.jar' \
    -O 'https://github.com/yoshinorin/gitbucket-monitoring-plugin/releases/download/v5.1.0/gitbucket-monitorting-plugin-5.1.0.jar' \
    -O 'https://github.com/alexandremenif/gitbucket-mirror-plugin/releases/download/v1.4.0/gitbucket-mirror-plugin-1.4.0.jar' \
    -O 'https://github.com/gitbucket-plugins/gitbucket-explorer-plugin/releases/download/9.0.0/gitbucket-explorer-plugin-9.0.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-code-highlighter-plugin/releases/download/v1.6.0/gitbucket-code-highlighter-plugin-1.6.0.jar' \
    -O 'https://github.com/kaz-on/gitbucket-popovers-plugin/releases/download/v1.0.0/gitbucket-popovers-plugin-1.0.0.jar' \
    -O 'https://github.com/kounoike/gitbucket-html5media-plugin/releases/download/1.2.2/gitbucket-html5media-plugin-1.2.2.jar' \
    -O 'https://github.com/onukura/gitbucket-swagger-plugin/releases/download/1.0.7/gitbucket-swagger-plugin-1.0.7.jar'
  SAVE ARTIFACT plugins

git: # only git binary, requires ld, libc, libpthread, libz
  FROM docker.io/bitnami/git
  SAVE ARTIFACT --keep-own /opt/bitnami/git/bin/git

rootfs:
  COPY --keep-own +git/git rootfs/usr/bin/
  COPY --keep-own base+execline/background rootfs/usr/bin/
  COPY --chown=nonroot:nonroot +gitbucket.war/gitbucket.war rootfs/home/nonroot/
  COPY --chown=nonroot:nonroot --chmod=644 database.conf rootfs/home/nonroot/.gitbucket/
  COPY --chown=nonroot:nonroot +plugins/plugins rootfs/home/nonroot/.gitbucket/plugins

  COPY --keep-own ../mariadb+rootfs/rootfs rootfs
  COPY --keep-own ../mariadb+var/var rootfs/var
  RUN $pacman -S mariadb
  RUN sudo mkdir -p /run/mysqld && sudo chown nonroot:nonroot /run/mysqld && \
    mariadbd --datadir=$HOME/rootfs/var/lib/mysql & \
    sleep 2 && mariadb -u root --password=secret -e 'CREATE DATABASE gitbucket' && \
    killall mariadbd
  DO builder+ROOTFS


container:
  # BUILD +plugins-container
  FROM ../openjdk+container
  COPY --keep-own +rootfs/rootfs /
  ENTRYPOINT [ "background", "mariadbd", "", "java", "-jar" ]
  CMD [ "gitbucket.war", "--port=8080" ]
  EXPOSE 8080
  DO builder+PUSH --name=gitbucket --tag=$version
