FROM docker.io/library/archlinux:base-devel

RUN sed -i /etc/pacman.conf -e 's/NoProgress/#NoProgress/' -e '/NoExtract.*locale/d'
# && \
# printf '%s\n%s\n' 'NoExtract = !usr/share/locale/ja/*' 'NoExtract = !usr/share/i18n/locales/ja_JP/*' >> /etc/pacman.conf

COPY --chmod=644 mirrorlist /etc/pacman.d/mirrorlist

RUN pacman -Syu --noconfirm glibc git moreutils busybox

COPY --chmod=644 locale.gen /etc/locale.gen
RUN locale-gen

RUN useradd --uid 65532 --gid 65532 -m -s /usr/bin/nologin nonroot && \
  printf '%s\n' 'nonroot ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
USER nonroot
WORKDIR /home/nonroot

RUN git clone https://aur.archlinux.org/paru-bin /tmp/paru
RUN cd /tmp/paru && makepkg -sir --noconfirm

RUN rm -rf /tmp/*